# Generated by Django 3.2.6 on 2021-08-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.AddField(
            model_name='classes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
