# Generated by Django 3.2.6 on 2021-08-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210826_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
