# Generated by Django 3.2.7 on 2021-09-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='item_colour',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
