# Generated by Django 3.2.6 on 2021-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('colours', models.BooleanField(blank=True, default=False, null=True)),
                ('black', models.BooleanField(default=False)),
                ('pink', models.BooleanField(default=False)),
                ('yellow', models.BooleanField(default=False)),
                ('red', models.BooleanField(default=False)),
                ('green', models.BooleanField(default=False)),
                ('blue', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
