# Generated by Django 3.2.5 on 2021-08-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210814_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colours',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
