# Generated by Django 3.2.5 on 2021-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_item_item_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='colour_changes',
            field=models.BooleanField(default=False),
        ),
    ]
