# Generated by Django 3.2.5 on 2021-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_colour_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_colour',
            field=models.CharField(blank=True, choices=[('Black', False), ('Pink', False), ('Red', False), ('Blue', False), ('Green', False)], max_length=20, null=True),
        ),
    ]
