# Generated by Django 3.2.5 on 2021-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_item_item_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='colour_changes',
            new_name='black',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_colour',
        ),
        migrations.AddField(
            model_name='item',
            name='blue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='pink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='yellow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='colours',
            field=models.BooleanField(default=False),
        ),
    ]
