# Generated by Django 3.2.5 on 2021-08-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210821_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='black',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='blue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='colours',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='green',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pink',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='red',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='yellow',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
