# Generated by Django 3.2.5 on 2021-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210821_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='black',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='blue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='green',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='pink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='red',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='yellow',
            field=models.BooleanField(default=False),
        ),
    ]
